'use client';

import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Brain, Check, ClipboardList, FileText, Lightbulb, Plus, Search, ShieldCheck, Upload, X } from 'lucide-react';
import { AiIcon } from '@/components/ai-icon';
import { ModalPortal } from '@/components/modal-portal';
type Patient = { id: string; nome: string; escolaridade?: string; observacoes?: string };
type Assessment = { id: string; patientId: string; title: string; startedAt: string; step: number; anamnesis: Record<string, string>; tests: string[]; hypotheses: string; hypothesisData: Record<string, string>; report: string; reportData: Record<string, string>; feedback: string; feedbackData: Record<string, string> };
const fields = [['historico_familiar','Histórico Familiar','Descreva o histórico familiar...'],['desenvolvimento','Desenvolvimento Neuropsicomotor','Marcos do desenvolvimento...'],['historico_escolar','Histórico Escolar','Desempenho e adaptação escolar...'],['historico_ocupacional','Histórico Ocupacional','Histórico de trabalho...'],['historico_medico','Histórico Médico','Condições, internações, cirurgias e tratamentos...']];
const testDomains = [
  { title: 'Inteligência e capacidade global', icon: 'QI', description: 'Raciocínio, compreensão, memória de trabalho e velocidade de processamento.', tests: ['WAIS · adultos a partir de 16 anos', 'WISC · crianças e adolescentes', 'SON-R · avaliação não verbal', 'Matrizes Progressivas de Raven · raciocínio não verbal'] },
  { title: 'Atenção e concentração', icon: 'AT', description: 'Atenção seletiva, sustentada, alternada, inibição e velocidade.', tests: ['Teste de Atenção por Cancelamento', 'd2-R · atenção concentrada', 'Stroop · controle inibitório', 'TAVIS-4 · atenção visual'] },
  { title: 'Memória e aprendizagem', icon: 'ME', description: 'Aprendizagem, retenção, reconhecimento e memória verbal ou visuoespacial.', tests: ['RAVLT · aprendizagem verbal', 'Figura Complexa de Rey · memória visuoespacial', 'WMS · investigação ampla da memória'] },
  { title: 'Funções executivas', icon: 'FE', description: 'Flexibilidade cognitiva, planejamento, alternância e solução de problemas.', tests: ['TMT A/B · velocidade e alternância', 'WCST · flexibilidade e abstração', 'Torre de Londres · planejamento'] },
  { title: 'Linguagem e visuoespacial', icon: 'LV', description: 'Nomeação, compreensão verbal, praxia e organização visuoconstrutiva.', tests: ['Teste de Nomeação de Boston', 'Teste do Desenho do Relógio', 'Teste de Token · compreensão verbal'] },
];
const instrumentCatalog = [
  { name: 'WAIS', domain: 'Inteligência e capacidade global', ages: 'Adultos a partir de 16 anos', measures: 'Funcionamento intelectual global e índices cognitivos', fields: ['QI Total', 'Compreensão Verbal', 'Raciocínio/Organização Perceptual', 'Memória Operacional', 'Velocidade de Processamento'] },
  { name: 'WISC', domain: 'Inteligência e capacidade global', ages: 'Crianças e adolescentes', measures: 'Funcionamento intelectual global e perfil de índices', fields: ['QI Total', 'Compreensão Verbal', 'Visuoespacial', 'Raciocínio Fluido', 'Memória Operacional', 'Velocidade de Processamento'] },
  { name: 'SON-R', domain: 'Inteligência e capacidade global', ages: 'Conforme edição e manual', measures: 'Inteligência não verbal e raciocínio', fields: ['Escore total', 'Escala de Execução', 'Escala de Raciocínio'] },
  { name: 'Matrizes Progressivas de Raven', domain: 'Inteligência e capacidade global', ages: 'Conforme forma utilizada', measures: 'Raciocínio abstrato não verbal', fields: ['Acertos', 'Escore padronizado/percentil'] },
  { name: 'Teste de Atenção por Cancelamento', domain: 'Atenção e concentração', ages: 'Conforme manual', measures: 'Atenção seletiva, sustentada e alternância', fields: ['Acertos', 'Erros', 'Omissões', 'Tempo'] },
  { name: 'd2-R', domain: 'Atenção e concentração', ages: 'Conforme manual', measures: 'Atenção concentrada e velocidade de processamento', fields: ['Itens processados', 'Erros de omissão', 'Erros de comissão', 'Desempenho de concentração'] },
  { name: 'Stroop', domain: 'Atenção e concentração', ages: 'Conforme versão e normas', measures: 'Inibição e controle de interferência', fields: ['Tempo condição 1', 'Erros condição 1', 'Tempo condição 2', 'Erros condição 2', 'Tempo condição de interferência', 'Erros de interferência'] },
  { name: 'TAVIS-4', domain: 'Atenção e concentração', ages: 'Crianças e adolescentes de 6 a 17 anos', measures: 'Seletividade, alternância e sustentação da atenção visual', fields: ['Tempo médio de reação', 'Erros por omissão', 'Erros por ação'] },
  { name: 'RAVLT', domain: 'Memória e aprendizagem', ages: 'Conforme normas da versão', measures: 'Aprendizagem verbal, interferência, evocação e reconhecimento', fields: ['A1', 'A2', 'A3', 'A4', 'A5', 'Lista B', 'A6 pós-interferência', 'A7 tardia', 'Reconhecimento', 'Intrusões/perseverações'] },
  { name: 'Figura Complexa de Rey', domain: 'Memória e aprendizagem', ages: 'Conforme manual', measures: 'Visuoconstrução, planejamento e memória visuoespacial', fields: ['Cópia', 'Tempo da cópia', 'Evocação imediata', 'Evocação tardia', 'Estratégia/organização'] },
  { name: 'WMS', domain: 'Memória e aprendizagem', ages: 'Conforme edição e manual', measures: 'Perfil amplo de memória', fields: ['Memória Auditiva', 'Memória Visual', 'Memória Imediata', 'Memória Tardia', 'Memória de Trabalho'] },
  { name: 'TMT A/B', domain: 'Funções executivas', ages: 'Conforme normas utilizadas', measures: 'Velocidade, atenção e alternância cognitiva', fields: ['Tempo TMT-A', 'Erros TMT-A', 'Tempo TMT-B', 'Erros TMT-B', 'Razão B/A'] },
  { name: 'WCST', domain: 'Funções executivas', ages: 'Conforme versão e manual', measures: 'Flexibilidade, abstração e aprendizagem por feedback', fields: ['Categorias completadas', 'Erros totais', 'Erros perseverativos', 'Respostas perseverativas', 'Fracasso em manter contexto'] },
  { name: 'Torre de Londres', domain: 'Funções executivas', ages: 'Conforme versão e manual', measures: 'Planejamento e resolução de problemas', fields: ['Escore total', 'Movimentos', 'Tempo de planejamento', 'Tempo de execução', 'Violações de regra'] },
  { name: 'Teste de Nomeação de Boston', domain: 'Linguagem e visuoespacial', ages: 'Conforme normas utilizadas', measures: 'Nomeação por confrontação visual e acesso lexical', fields: ['Acertos espontâneos', 'Acertos com pista semântica', 'Acertos com pista fonêmica', 'Erros'] },
  { name: 'Teste do Desenho do Relógio', domain: 'Linguagem e visuoespacial', ages: 'Conforme sistema de correção', measures: 'Visuoconstrução, planejamento e organização espacial', fields: ['Escore total', 'Organização espacial', 'Posicionamento dos números', 'Ponteiros/horário'] },
  { name: 'Teste de Token', domain: 'Linguagem e visuoespacial', ages: 'Conforme versão e manual', measures: 'Compreensão verbal e execução de ordens', fields: ['Acertos', 'Erros', 'Partes/complexidade', 'Observação qualitativa'] },
];
const instruments = instrumentCatalog.map(item => `${item.name}|${item.domain}`);
const childTopics = [
  ['Motivo do encaminhamento e percepção dos pais','O que investigar: motivos da busca, percepção dos pais, expectativas e coerência entre a queixa e o comportamento observado. Perguntas: Quem encaminhou e por quê? Qual a expectativa da família? A criança/adolescente entende o motivo do atendimento? Como reagiu?'],
  ['Desenvolvimento infantil','O que investigar: marcos do desenvolvimento, vínculo parental e complicações gestacionais ou no parto. Perguntas: A gravidez foi planejada? Houve intercorrências? Como foi o parto? Houve internação, icterícia ou necessidade de oxigenação? Quem cuidou nos primeiros dias? Como foi a amamentação? Quando sustentou a cabeça, sentou, engatinhou, andou e falou?'],
  ['Vida escolar e aprendizado','O que investigar: histórico escolar, rendimento, adaptação, relações e possíveis rótulos que afetaram a autoestima. Perguntas: Qual é a escola e a série atual? É pública ou privada? Já houve reprovação ou troca de escola? Existem dificuldades em matérias específicas? Quem apoia os estudos? Como reage às notas? A escola já chamou os responsáveis por comportamento?'],
  ['Rotina, sono e alimentação','O que investigar: organização da rotina, supervisão, sobrecarga, higiene, sono e alimentação. Perguntas: Quais atividades realiza? Há atividades extracurriculares e quem as escolheu? Como são horários, qualidade do sono e despertares? Faz todas as refeições e com quem? Quem supervisiona banho e higiene?'],
  ['Relações familiares','O que investigar: configuração familiar, qualidade dos vínculos, figuras de acolhimento e autoridade, perdas e afastamentos. Perguntas: Com quem mora? Como são as relações em casa? Houve separações, mortes ou perdas importantes? Pais ou responsáveis já fizeram psicoterapia ou tratamento psiquiátrico?'],
  ['Histórico de saúde','O que investigar: saúde física e mental, tratamentos anteriores, medicamentos e reação aos cuidados. Perguntas: Há doença diagnosticada? Usa medicação, qual e há quanto tempo? Já houve internação ou doença grave? Já realizou acompanhamento psicológico, psiquiátrico, fonoaudiológico ou psicopedagógico?'],
  ['Histórico familiar de sofrimento psíquico','O que investigar: fatores de risco familiares e eventos traumáticos. Perguntas: Há transtornos mentais, dependência de substâncias ou suicídio na família? Existe histórico de violência física, sexual ou psicológica? A criança testemunhou ou vivenciou eventos traumáticos?'],
  ['Expectativas e valores familiares','O que investigar: crenças, valores e expectativas familiares. Perguntas: Quais valores desejam transmitir? Qual a expectativa para escolaridade e futuro? Existem crenças religiosas, costumes ou tradições relevantes?'],
  ['Vínculo com a terapia','O que investigar: compreensão, adesão e conforto com o processo terapêutico. Perguntas ao paciente: Você sabe por que está vindo? Quis vir ou alguém pediu? Gosta e se sente bem aqui? Já fez terapia antes? Como foi?'],
  ['Vida escolar — percepção do paciente','O que investigar: experiência subjetiva na escola, desempenho, relações e sofrimento como bullying. Perguntas: Em qual escola e série estuda? Gosta da escola? Tem amigos ou se sente sozinho? Quais matérias são fáceis ou difíceis? Já foi chamado à coordenação? Como se relaciona com professores e inspetores?'],
  ['Rotina e interesses','O que investigar: equilíbrio entre obrigações, lazer, autonomia e atividades prazerosas. Perguntas: O que faz durante a semana e no tempo livre? Faz atividades fora da escola? Gosta delas? Quem escolheu? Pode optar por sair? Quais jogos, músicas, séries ou passatempos prefere?'],
  ['Sono, alimentação e higiene','O que investigar: autocuidado, autonomia e possíveis falhas na rotina. Perguntas: Dorme bem e em qual horário? Tem pesadelos ou despertares? Alimenta-se bem ou pula refeições? Toma banho sozinho? Quem ajuda?'],
  ['Relações familiares — percepção do paciente','O que investigar: percepção do convívio, vínculos e papéis familiares. Perguntas: Com quem mora? Como é a relação com essas pessoas? Tem irmãos e como convivem? Quem mais cuida e quem mais impõe limites?'],
  ['Reações e comportamentos','O que investigar: manejo da frustração, sofrimento emocional e resposta a limites. Perguntas: O que faz quando recebe bronca ou castigo? Chora, bate portas ou fica em silêncio? Já se machucou por tristeza ou raiva? Como se sente depois de ser castigado?'],
  ['Sexualidade e segurança','Para adolescentes. O que investigar: sexualidade, consentimento, proteção, pressão e exposição indevida. Perguntas: Já teve relação sexual? Foi por vontade própria? Sabe como se proteger? Usa preservativo? Pais ou amigos sabem? Alguém já compartilhou conteúdo íntimo sem permissão?'],
  ['Saúde e corpo','O que investigar: percepção corporal, adoecimento, dor e possíveis manifestações psicossomáticas. Perguntas: Tem alguma doença ou usa remédio? Vai ao médico com frequência? Sente dores de cabeça, barriga, tontura ou enjoo? Usa óculos ou aparelho?']
];
const adultTopics = [
  ['Estado civil, relacionamentos e filhos','Informe o estado civil. Se solteiro, descreva relacionamentos recentes. Registre filhos, nomes e idades quando adequado.'],
  ['Situação de vida atual','Com quem vive atualmente? Como é a residência e o ambiente em que mora?'],['Sustento e situação financeira','Como está se sustentando atualmente? Investigue trabalho, renda, apoio de terceiros e dificuldades financerias relevantes.'],
  ['Histórico ocupacional','Descreva empregos, trabalhos e atividades profissionais anteriores, duração, motivos de saída e períodos de afastamento.'],['Escolaridade','Qual foi a última série ou formação concluída e quando? Investigue dificuldades, interrupções e experiências relevantes.'],
  ['Relações no trabalho','Como são ou foram as relações com colegas, chefias, subordinados e ambiente profissional?'],
  ['Problema atual e funcionamento','Razões para indicação do tratamento e descrição detalhada dos problemas atuais. Investigue situações em que ocorrem, situações evitadas, funcionamento de 1 a 10, impacto percentual, áreas mais e menos afetadas, tarefa mais difícil, reações físicas e emocionais, pensamentos antes/durante/depois, comportamentos, padrões de melhora ou piora, fatores ambientais, estratégias já utilizadas, formas de proteção e habilidades que gostaria de desenvolver.'],
  ['Outros estressores atuais','Além do problema principal, quais outros estressores estão presentes atualmente? Avalie intensidade, duração e impacto.'],
  ['Humor, sono, apetite e risco','Como descreve o humor atual de 1 a 10? Se deprimido, há quanto tempo? Houve perda de interesse? Como vê o futuro? Como estão sono e apetite? Já pensou em se ferir? Diferencie autolesão e comportamento suicida; registre frequência, método, tentativas, histórico familiar e fatores protetivos. Investigue tratamentos anteriores e eficácia.'],
  ['Outras preocupações psicológicas','Há outras preocupações de ordem psicológica, emocional, comportamental ou cognitiva que ainda não foram discutidas?'],
  ['Saúde física e medicações','Há preocupações físicas atuais? Registre condições médicas, exames, tratamentos e medicações com tipo, dose e frequência.'],
  ['Uso de álcool e outras substâncias','Investigue uso atual de álcool, drogas, tabaco e cafeína. Houve abuso ou dependência no passado? Já realizou tratamento relacionado a substâncias?'],
  ['Participação comunitária','Participa atualmente de programa comunitário, religioso, voluntário, grupo de apoio ou atividade coletiva?'],['Lazer e interesses','O que gosta de fazer nas horas de lazer? Investigue frequência, satisfação e barreiras atuais.'],
  ['Histórico dos problemas atuais','Quando os problemas começaram? Houve incidente precipitante? Como era na infância e adolescência? Existiram dificuldades de desenvolvimento, escola, família, abuso ou relacionamentos? Já buscou ajuda psicológica ou psiquiátrica? Há histórico familiar de ansiedade, depressão, substâncias ou problemas semelhantes?'],
  ['Composição familiar','Quem faz parte da família? Registre nomes de pais e irmãos, idades, locais onde moram e vínculos relevantes.'],
  ['Rede de apoio e emergência','De quem está mais próximo e mais distante na família? Quem procuraria para apoio? Quem acionaria em crise ou emergência?'],
  ['Informações não abordadas','Pergunte se alguma informação importante foi esquecida ou não abordada durante a entrevista.'],
  ['Autodescrição, forças e dificuldades','Peça três ou quatro adjetivos para descrever a si mesmo, incluindo forças e dificuldades. Se necessário, considere a percepção de alguém próximo.'],
  ['Expectativas e metas do tratamento','Quais são as expectativas e metas? Registre uma ou duas mudanças desejadas em relação aos problemas discutidos.'],
  ['Resultado desejado','Supondo que o tratamento tenha sucesso, qual seria o resultado esperado? Registre o objetivo declarado.'],
  ['Objetivo observável','Se o comportamento pudesse ser observado frequentemente, o que a pessoa estaria fazendo de diferente? Transforme a meta em comportamento observável.'],
  ['Percepção de mudanças por terceiros','O que outras pessoas observariam quando o resultado positivo fosse alcançado?'],
  ['Diferença entre estado atual e desejado','Como o resultado desejado difere da situação atual? O que acontece ou é feito hoje que precisaria mudar?'],
  ['Perguntas e próximos passos','O paciente tem alguma pergunta? Explique o que acontecerá a seguir, alinhe expectativas e registre os próximos passos.']
];

export function NeuropsychAssessment({ patient }: { patient: Patient }) {
  const [item, setItem] = useState<Assessment | null>(null); const [manual, setManual] = useState(false); const [search, setSearch] = useState(''); const [selectedInstrument, setSelectedInstrument] = useState('');
  const [ageGroup, setAgeGroup] = useState('Todas'); const [selectedDomain, setSelectedDomain] = useState('Todos');
  const [manualScores, setManualScores] = useState<Record<string, string>>({}); const [manualNotes, setManualNotes] = useState('');
  const [anamnesisModel] = useState<'estruturada'|'criancas'|'adultos'>('estruturada'); const [sendMode, setSendMode] = useState(false); const [generatedLink, setGeneratedLink] = useState('');
  const [formResponses, setFormResponses] = useState<Array<{ id: string; form_titulo: string; data_envio: string; respostas: Array<{ pergunta: string; resposta: string }> }>>([]);

  useEffect(() => {
    fetch(`/api/neuroavaliacoes?patientId=${patient.id}`).then(r => r.json()).then((data: Assessment[]) => setItem(data[0] ? { ...data[0], hypothesisData: { status: 'Em investigação', confianca: 'Baixa', ...(data[0].hypothesisData || {}) }, reportData: { titulo: 'Laudo Psicológico – Avaliação Neuropsicológica', ...(data[0].reportData || {}) }, feedbackData: { status: 'A agendar', destinatario: 'Pessoa avaliada', modalidade: 'Presencial', ...(data[0].feedbackData || {}) } } : null));
    if (patient.id) {
      fetch(`/api/pacientes/${patient.id}/central`)
        .then(r => r.json())
        .then(d => {
          if (Array.isArray(d?.respostas_formulario)) {
            setFormResponses(d.respostas_formulario);
          }
        })
        .catch(() => {});
    }
  }, [patient.id]);

  async function persist(next: Assessment) { setItem(next); await fetch('/api/neuroavaliacoes', { method: 'PUT', headers: {'Content-Type':'application/json'}, body: JSON.stringify(next) }); }
  async function create() { const r = await fetch('/api/neuroavaliacoes', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ patientId:patient.id, patientName:patient.nome }) }); setItem(await r.json()); }
  const catalog = useMemo(() => instruments.filter(i => i.toLowerCase().includes(search.toLowerCase()) && (selectedDomain === 'Todos' || i.endsWith(`|${selectedDomain}`))), [search, selectedDomain]);
  const selectedDetails = instrumentCatalog.find(instrument => instrument.name === selectedInstrument);
  if (!item) return <div className="neuro-empty panel-card"><Brain /><h2>Avaliação Neuropsicológica</h2><p>Organize anamnese, testes, hipóteses, laudo e devolutiva em um fluxo clínico integrado.</p><button className="button-primary" onClick={create}><Plus /> Nova avaliação</button></div>;
  const update = (change: Partial<Assessment>) => persist({ ...item, ...change });
  return <section className="neuro-module"><header className="neuro-title"><div><h2>{item.title}</h2><span>iniciada em {new Date(item.startedAt).toLocaleDateString('pt-BR')}</span></div><button className="button-primary" onClick={create}><Plus /> Nova avaliação</button></header>
    <nav className="neuro-steps">{['Anamnese','Testes','Hipóteses','Laudo','Devolutiva'].map((label,index)=><button key={label} className={item.step===index+1?'active':''} onClick={()=>update({step:index+1})}><i>{index+1}</i>{label}</button>)}</nav>
    <div className="neuro-layout"><main>
      {item.step===1 && <div className="neuro-card anamnesis-workspace"><div className="neuro-card-heading"><div><h3>Registrar Anamnese</h3><p>Preencha durante a entrevista ou envie para o paciente/responsável.</p></div><button><Upload /> Anexar PDF</button></div>
        {formResponses.length > 0 && (
          <div className="mb-4 p-4 rounded-xl border border-indigo-200 dark:border-indigo-900 bg-indigo-50/50 dark:bg-indigo-950/30">
            <div className="flex justify-between items-center mb-3">
              <div className="flex items-center gap-2">
                <ClipboardList className="w-4 h-4 text-accent" />
                <strong className="text-xs font-bold text-indigo-950 dark:text-indigo-200">Respostas do formulário prévio</strong>
                <span className="text-[10px] px-2 py-0.5 rounded-full bg-indigo-100 dark:bg-indigo-900 text-indigo-700 dark:text-indigo-300 font-bold">
                  {formResponses.length} recebido(s)
                </span>
              </div>
              <button
                type="button"
                className="btn-action btn-compact text-[11px] py-0.5 px-2"
                onClick={() => {
                  const text = formResponses.map(f => `--- ${f.form_titulo} ---\n` + f.respostas.map(r => `• ${r.pergunta}\nR: ${r.resposta}`).join('\n\n')).join('\n\n');
                  navigator.clipboard.writeText(text);
                }}
              >
                Copiar respostas
              </button>
            </div>
            <div className="flex flex-col gap-2.5 max-h-60 overflow-y-auto pr-1">
              {formResponses.map((f, i) => (
                <details key={f.id || i} className="bg-white p-3.5 rounded-lg border border-slate-200 shadow-sm" open={i === 0}>
                  <summary className="font-semibold text-xs cursor-pointer text-slate-800 select-none">
                    {f.form_titulo} · <small className="text-slate-500 font-normal">{new Date(f.data_envio).toLocaleDateString('pt-BR')}</small>
                  </summary>
                  <div className="mt-3 pl-3 border-l-2 border-[#09A4B3] flex flex-col gap-2.5 text-xs">
                    {f.respostas.map((r, ri) => (
                      <div key={ri} className="bg-[#f8fafc] p-2.5 rounded border border-slate-200">
                        <span className="font-bold text-slate-700 block text-[11px] mb-0.5">{r.pergunta}</span>
                        <span className="text-slate-900 font-medium">{r.resposta}</span>
                      </div>
                    ))}
                  </div>
                </details>
              ))}
            </div>
          </div>
        )}
        <div className="anamnesis-toolbar"><div><button className={!sendMode?'active':''} onClick={()=>setSendMode(false)}>Preencher aqui</button><button className={sendMode?'active':''} onClick={()=>setSendMode(true)}>Enviar ao paciente</button></div></div>
        {sendMode ? <div className="anamnesis-send"><div className="anamnesis-progress"><span>Paciente e envio</span><strong>Modelo escolhido · selecione o paciente</strong><i><b style={{width: generatedLink?'100%':'50%'}} /></i><small>{generatedLink?'100%':'50%'}</small></div><div className="anamnesis-send-grid"><label><span>Modelo</span><strong>{anamnesisModel==='criancas'?'Crianças / Adolescentes':anamnesisModel==='adultos'?'Adulto · Jan Leonardi':'Anamnese clínica resumida'}</strong></label><label><span>Paciente</span><strong>{patient.nome}</strong></label></div><button className="button-primary" onClick={()=>setGeneratedLink(`${window.location.origin}/quiz?anamnese=${item.id}`)}>Gerar link</button>{generatedLink&&<div className="generated-anamnesis-link"><input readOnly value={generatedLink}/><button onClick={()=>navigator.clipboard.writeText(generatedLink)}>Copiar link</button></div>}</div> : anamnesisModel==='estruturada' ? <div className="anamnesis-fields">{fields.map(([key,label,placeholder])=><label key={key}><strong>{label}</strong><textarea value={item.anamnesis[key]||''} placeholder={placeholder} onChange={e=>setItem({...item,anamnesis:{...item.anamnesis,[key]:e.target.value}})} onBlur={()=>item&&persist(item)} /></label>)}</div> : <div className="anamnesis-template-preview"><header><div><span className="eyebrow">Prévia do modelo</span><h4>{anamnesisModel==='criancas'?'Modelo Crianças / Adolescentes':'Modelo Adulto · Jan Leonardi'}</h4><p>Visualização das perguntas que serão apresentadas antes do envio.</p></div><strong>{(anamnesisModel==='criancas'?childTopics:adultTopics).length} perguntas</strong></header>{(anamnesisModel==='criancas'?childTopics:adultTopics).map(([title,prompt],index)=><article key={title}><b>{String(index+1).padStart(2,'0')}</b><label><strong>{title}</strong><small>{prompt}</small><textarea value={item.anamnesis[`${anamnesisModel}_${index}`]||''} placeholder="Espaço para resposta do paciente." onChange={e=>setItem({...item,anamnesis:{...item.anamnesis,[`${anamnesisModel}_${index}`]:e.target.value}})} onBlur={()=>item&&persist(item)}/></label></article>)}</div>}
      </div>}
      {item.step===2 && <div className="neuro-tests-workspace">
        <div className="clinical-warning"><ShieldCheck /> A seleção da bateria é decisão do profissional e deve considerar faixa etária, queixa, objetivo, condições de aplicação, evidências científicas e situação atual do instrumento no SATEPSI.</div>
        <section className="neuro-card test-planning-card"><div className="neuro-card-heading"><div><h3>Planejamento da bateria neuropsicológica</h3><p>Organize os instrumentos por função cognitiva e escolha somente o necessário para responder às hipóteses da avaliação.</p></div><button onClick={()=>setManual(true)}><Plus /> Adicionar teste</button></div>
          <div className="test-planning-filters"><label>Faixa etária<select value={ageGroup} onChange={e=>setAgeGroup(e.target.value)}><option>Todas</option><option>Criança</option><option>Adolescente</option><option>Adulto</option><option>Idoso</option></select></label><label>Função investigada<select value={selectedDomain} onChange={e=>setSelectedDomain(e.target.value)}><option>Todos</option>{testDomains.map(domain=><option key={domain.title}>{domain.title}</option>)}</select></label></div>
          <div className="cognitive-domain-grid">{testDomains.filter(domain=>selectedDomain==='Todos'||selectedDomain===domain.title).map(domain=><article key={domain.title}><header><i>{domain.icon}</i><div><h4>{domain.title}</h4><p>{domain.description}</p></div></header><ul>{domain.tests.map(test=><li key={test}>{test}</li>)}</ul><button onClick={()=>{setSelectedDomain(domain.title);setManual(true)}}>Ver instrumentos</button></article>)}</div>
        </section>
      </div>}
      {item.step===3 && <div className="hypothesis-workspace">
        <div className="clinical-warning"><ShieldCheck /> Hipótese diagnóstica não é diagnóstico fechado. Deve ser fundamentada tecnicamente, testada contra os dados, contextualizada e revisada sempre que surgirem novas informações.</div>
        <section className="neuro-card"><div className="neuro-card-heading"><div><h3>Raciocínio diagnóstico estruturado</h3><p>Registre o que sustenta, contradiz e ainda precisa ser investigado antes de concluir.</p></div><button data-ai-action="organize-hypothesis" data-ai-title="Organizar com Aura" onClick={()=>update({hypothesisData:{...item.hypothesisData,status:'Em investigação',confianca:'Baixa',hipotese_principal:'Possibilidade clínica a investigar — definir condição e referência classificatória somente após integração dos dados.',evidencias:'Anamnese, observações e resultados convergentes ainda devem ser descritos.',contradicoes:'Registrar dados ausentes, inconsistentes ou incompatíveis com a hipótese.',diferenciais:'Listar condições alternativas, fatores emocionais, médicos, ambientais e do desenvolvimento.',contexto:'Considerar história, cultura, escolaridade, funcionamento prévio, medicações, sono e condições de aplicação.',proximos_passos:'Definir dados adicionais, fontes complementares, encaminhamentos e critérios de revisão.'}})}><AiIcon /> Organizar com Aura</button></div>
          <div className="hypothesis-fields">{([
            ['hipotese_principal','Hipótese principal e referência','Descreva a hipótese provisória. Se pertinente, informe CID/DSM ou outra referência reconhecida.'],
            ['evidencias','Evidências que sustentam','Dados da anamnese, observação, testes, escalas e fontes complementares que convergem.'],
            ['contradicoes','Evidências contrárias ou inconsistências','O que não se ajusta à hipótese? Há resultados divergentes ou explicações alternativas?'],
            ['diferenciais','Hipóteses diferenciais','Condições alternativas e como serão diferenciadas.'],
            ['contexto','Contexto e fatores de confusão','Cultura, escolaridade, desenvolvimento, sono, medicações, substâncias, condições médicas e ambientais.'],
            ['impacto','Gravidade e impacto funcional','Frequência, duração, sofrimento e prejuízo nos diferentes contextos de vida.'],
            ['proximos_passos','Dados faltantes e próximos passos','O que ainda precisa ser investigado, confirmado, encaminhado ou reavaliado?'],
          ] as const).map(([key,label,placeholder])=><label key={key}><strong>{label}</strong><textarea value={item.hypothesisData[key]||''} onChange={e=>setItem({...item,hypothesisData:{...item.hypothesisData,[key]:e.target.value}})} onBlur={()=>item&&persist(item)} placeholder={placeholder}/></label>)}</div>
        </section>
        <section className="neuro-card hypothesis-synthesis"><div><h3>Síntese clínica provisória</h3><p>Redija uma conclusão coerente com a demanda, os procedimentos e a análise. Evite afirmar além do que os dados permitem.</p></div><textarea className="neuro-large-text" value={item.hypotheses} onChange={e=>setItem({...item,hypotheses:e.target.value})} onBlur={()=>item&&persist(item)} placeholder="Integre as hipóteses, o grau de sustentação, as limitações e as recomendações..."/><p><AlertTriangle /> A classificação diagnóstica, quando utilizada, deve ter base técnico-científica e referência atual. A responsabilidade pela interpretação e conclusão é do profissional.</p></section>
      </div>}
      {item.step===4 && <div className="report-workspace">
        <section className="neuro-card report-heading"><div><span className="eyebrow">DOCUMENTO PSICOLÓGICO</span><h3>Laudo Psicológico – Avaliação Neuropsicológica</h3><p>Estrutura conforme a Resolução CFP nº 06/2019. Registre somente informações necessárias à finalidade do documento.</p></div><button data-ai-action="organize-report" data-ai-title="Organizar rascunho" className="button-primary" onClick={()=>{const generated={...item.reportData,titulo:'Laudo Psicológico – Avaliação Neuropsicológica',identificacao:`Pessoa avaliada: ${patient.nome}\nSolicitante: informar\nFinalidade: informar\nProfissional responsável e CRP: informar`,demanda:patient.observacoes||'Descrever o motivo da avaliação, quem forneceu as informações e a finalidade da solicitação.',procedimento:`Descrever referencial teórico-metodológico, fontes de informação, número e duração dos encontros.\nInstrumentos e técnicas registrados: ${item.tests.join('; ')||'informar'}.`,analise:`Integrar anamnese, observações clínicas e resultados, considerando contexto histórico, social e funcional.\n\n${Object.values(item.anamnesis).filter(Boolean).join('\n')}`,conclusao:`Síntese clínica provisória:\n${item.hypotheses||'A conclusão deverá responder à demanda e explicitar limites, recomendações e encaminhamentos.'}`,referencias:'Informar as fontes científicas, manuais técnicos e classificações diagnósticas efetivamente utilizados.'};update({reportData:generated,report:Object.entries(generated).map(([key,value])=>`${key.toUpperCase()}\n${value}`).join('\n\n')})}}><AiIcon /> Organizar rascunho</button></section>
        <div className="clinical-warning"><ShieldCheck /> A geração é apoio à redação. O profissional deve revisar a pertinência, fundamentação, sigilo, conclusão, referências e destinatário antes de emitir ou assinar.</div>
        <section className="neuro-card report-fields">{([
          ['identificacao','1. Identificação','Nome da pessoa atendida, solicitante, finalidade, nome do profissional e CRP.'],
          ['demanda','2. Descrição da demanda','Motivo da busca, origem das informações e demanda que levou à avaliação.'],
          ['procedimento','3. Procedimento','Raciocínio técnico-científico, referencial, pessoas ouvidas, fontes, técnicas, instrumentos, número e duração dos encontros.'],
          ['analise','4. Análise','Integração narrativa e fundamentada dos dados, sem transcrição mecânica de sessões ou resultados isolados.'],
          ['conclusao','5. Conclusão','Resposta à demanda, hipóteses ou diagnóstico quando sustentados, limites, recomendações, encaminhamentos e validade contextual.'],
          ['referencias','6. Referências','Fontes científicas, manuais e classificações efetivamente utilizadas.'],
        ] as const).map(([key,label,placeholder])=><label key={key}><strong>{label}</strong><small>{placeholder}</small><textarea value={item.reportData[key]||''} placeholder={placeholder} onChange={e=>setItem({...item,reportData:{...item.reportData,[key]:e.target.value}})} onBlur={()=>item&&persist(item)}/></label>)}</section>
        <section className="neuro-card report-checklist"><h3>Revisão antes da emissão</h3><div><span><Check /> Linguagem clara e acessível ao destinatário</span><span><Check /> Conclusão coerente com demanda, procedimentos e análise</span><span><Check /> Apenas informações necessárias e pertinentes</span><span><Check /> Referências científicas informadas</span><span><Check /> Local, data, identificação profissional, CRP e assinatura</span><span><Check /> Entrevista devolutiva planejada</span></div></section>
      </div>}
      {item.step===5 && <div className="feedback-workspace">
        <section className="neuro-card report-heading"><div><span className="eyebrow">ENTREVISTA DEVOLUTIVA</span><h3>Devolutiva da avaliação</h3><p>Planeje a comunicação dos resultados, esclareça o documento e registre a entrega de forma adequada ao destinatário.</p></div><button data-ai-action="organize-feedback" data-ai-title="Organizar roteiro" className="button-primary" disabled={!item.report&&!Object.values(item.reportData||{}).some(Boolean)} onClick={()=>{const conclusion=item.reportData?.conclusao||item.hypotheses||'';const next={...item.feedbackData,resultados:conclusion,orientacoes:item.feedbackData.orientacoes||'Registrar recomendações, encaminhamentos e próximos passos discutidos.',registro:item.feedbackData.registro||'Registrar dúvidas, reações, compreensão e acordos estabelecidos durante a entrevista.'};update({feedbackData:next,feedback:Object.entries(next).map(([key,value])=>`${key.replaceAll('_',' ')}: ${value}`).join('\n\n')})}}><AiIcon /> Organizar roteiro</button></section>
        <div className="clinical-warning"><ShieldCheck /> A devolutiva deve esclarecer verbalmente os resultados e o documento. Adapte a linguagem, preserve o sigilo e compartilhe somente o necessário para a finalidade e para cada destinatário.</div>
        <section className="neuro-card feedback-planning"><h3>Planejamento e realização</h3><div className="feedback-status-grid"><label><span>Status</span><select value={item.feedbackData.status||'A agendar'} onChange={e=>setItem({...item,feedbackData:{...item.feedbackData,status:e.target.value}})} onBlur={()=>item&&persist(item)}><option>A agendar</option><option>Agendada</option><option>Realizada</option><option>Não realizada</option></select></label><label><span>Destinatário principal</span><select value={item.feedbackData.destinatario||'Pessoa avaliada'} onChange={e=>setItem({...item,feedbackData:{...item.feedbackData,destinatario:e.target.value}})} onBlur={()=>item&&persist(item)}><option>Pessoa avaliada</option><option>Responsável legal</option><option>Pessoa avaliada e responsável</option><option>Instituição solicitante</option><option>Equipe multiprofissional</option></select></label><label><span>Data</span><input type="date" value={item.feedbackData.data||''} onChange={e=>setItem({...item,feedbackData:{...item.feedbackData,data:e.target.value}})} onBlur={()=>item&&persist(item)}/></label><label><span>Modalidade</span><select value={item.feedbackData.modalidade||'Presencial'} onChange={e=>setItem({...item,feedbackData:{...item.feedbackData,modalidade:e.target.value}})} onBlur={()=>item&&persist(item)}><option>Presencial</option><option>Online</option><option>Outra</option></select></label></div>
        <div className="feedback-fields">{([
          ['participantes','Participantes','Identifique quem participou e sua relação com a pessoa avaliada.'],
          ['resultados','Resultados comunicados','Registre a síntese explicada, incluindo recursos, dificuldades, limites e caráter contextual dos achados.'],
          ['orientacoes','Orientações e encaminhamentos','Recomendações, possibilidades de cuidado, adaptações e próximos passos discutidos.'],
          ['registro','Compreensão, dúvidas e acordos','Registre dúvidas, reações relevantes, compreensão demonstrada e decisões compartilhadas.'],
          ['entrega','Entrega do documento','Informe o documento entregue, meio de entrega e identificação do protocolo de recebimento.'],
        ] as const).map(([key,label,placeholder])=><label key={key}><strong>{label}</strong><small>{placeholder}</small><textarea value={item.feedbackData[key]||''} placeholder={placeholder} onChange={e=>setItem({...item,feedbackData:{...item.feedbackData,[key]:e.target.value}})} onBlur={()=>item&&persist(item)}/></label>)}</div>
        {item.feedbackData.status==='Não realizada'&&<label className="feedback-impossibility"><strong>Motivo da impossibilidade</strong><small>Registre as razões e as tentativas de contato ou oferta da devolutiva.</small><textarea value={item.feedbackData.motivo||''} onChange={e=>setItem({...item,feedbackData:{...item.feedbackData,motivo:e.target.value}})} onBlur={()=>item&&persist(item)}/></label>}</section>
        <section className="neuro-card report-checklist"><h3>Conferência da devolutiva</h3><div><span><Check /> Linguagem compreensível ao destinatário</span><span><Check /> Resultados e limites explicados</span><span><Check /> Espaço para dúvidas e manifestação</span><span><Check /> Recomendações e encaminhamentos discutidos</span><span><Check /> Protocolo de entrega registrado</span><span><Check /> Sigilo e finalidade preservados</span></div></section>
      </div>}
      <footer className="neuro-flow-footer"><button className="button-secondary" disabled={item.step===1} onClick={()=>update({step:item.step-1})}>Etapa anterior</button><span>Revise e valide todas as informações antes de avançar.</span><button className="button-primary" disabled={item.step===5} onClick={()=>update({step:item.step+1})}>Concluir etapa · avançar</button></footer>
    </main><aside className="neuro-case"><h4>O CASO</h4><p><span>Paciente</span><strong>{patient.nome}</strong></p><p><span>Escolaridade</span><strong>{patient.escolaridade||'—'}</strong></p><p><span>Queixa</span><strong>{patient.observacoes||'—'}</strong></p><h4><AlertTriangle /> ALERTAS CLÍNICOS</h4><em>Nenhum alerta clínico gerado nos testes desta avaliação.</em><h4><Lightbulb /> HIPÓTESES</h4><p>{item.hypotheses?'Hipóteses em revisão':'—'}</p><h4><ShieldCheck /> VALIDADOR</h4><div className="rehab-callout">Continue com Reabilitação Cognitiva<small>Transforme as hipóteses em plano estruturado.</small></div></aside></div>
    {manual&&<ModalPortal><div className="modal-overlay manual-test-overlay" onMouseDown={()=>setManual(false)}><div className="manual-test-modal" onMouseDown={e=>e.stopPropagation()}><header><div><h2>Registro manual de instrumentos</h2><p>Documente os resultados conforme o protocolo e o manual da edição utilizada.</p></div><button className="icon-button" onClick={()=>setManual(false)}><X /></button></header><div className="clinical-warning"><ShieldCheck /> O PSistem registra dados informados pelo profissional. Conversões normativas, interpretação e validação devem seguir o manual oficial e a situação atual no SATEPSI.</div><div className="manual-test-layout"><aside><h3><ClipboardList /> Catálogo por domínio</h3><label><Search/><input placeholder="Buscar instrumento..." value={search} onChange={e=>setSearch(e.target.value)}/></label><select className="manual-domain-filter" value={selectedDomain} onChange={e=>setSelectedDomain(e.target.value)}><option>Todos</option>{testDomains.map(domain=><option key={domain.title}>{domain.title}</option>)}</select><div>{catalog.map(entry=>{const [name,type]=entry.split('|');return <button className={selectedInstrument===name?'active':''} key={name} onClick={()=>{setSelectedInstrument(name);setManualScores({});setManualNotes('')}}><span>{name}</span><small>{type}</small></button>})}</div></aside><main>{selectedDetails?<><FileText/><h3>{selectedDetails.name}</h3><div className="instrument-metadata"><span><strong>Faixa etária</strong>{selectedDetails.ages}</span><span><strong>O que investiga</strong>{selectedDetails.measures}</span></div><div className="instrument-score-grid">{selectedDetails.fields.map(field=><label key={field}>{field}<input value={manualScores[field]||''} onChange={e=>setManualScores({...manualScores,[field]:e.target.value})} placeholder="Registrar conforme o protocolo" /></label>)}</div><label>Observações qualitativas<textarea value={manualNotes} onChange={e=>setManualNotes(e.target.value)} placeholder="Comportamento, compreensão, esforço, pausas, estratégias e intercorrências..." /></label><p className="instrument-caution"><AlertTriangle /> Não conclua diagnóstico a partir de um resultado isolado. Integre anamnese, observação, contexto e o conjunto da bateria.</p><button className="button-primary" onClick={()=>{const scores=Object.entries(manualScores).filter(([,value])=>value.trim()).map(([key,value])=>`${key}: ${value}`).join('; ');update({tests:[...item.tests,`${selectedDetails.name} · ${scores||'resultados registrados no protocolo'}${manualNotes.trim()?` · Observações: ${manualNotes.trim()}`:''}`]});setManual(false)}}>Salvar registro</button></>:<><AiIcon/><h3>Selecione um instrumento</h3><p>Os campos específicos de registro aparecerão aqui. Confirme a edição, faixa etária, normas e condições de uso antes da aplicação.</p></>}</main></div></div></div></ModalPortal>}
  </section>;
}
